### ISSUE TITLE
Remaining task to do 

### ISSUE THREAD

**Issue by AaryanAnand10** [ShashankaShekharSharma/Python-Gaming#4]
Interactive Fiction: Craft an interactive fiction game where players can read a story and make choices that alter the narrative. Implement branching storylines and multiple endings to keep players engaged.

Code Cracking Game: Develop a game where players are presented with encrypted messages and must use their coding knowledge to decipher them. The game can include different levels of difficulty with varying encryption techniques.

Command-Line RPG: Create a text-based role-playing game where players can create characters, level up, and battle monsters in a fantasy setting. Implement turn-based combat, character customization, and a quest system.

ASCII Art Drawing Game: Build a game where players can create ASCII art images using command-line characters. Provide a set of basic shapes and allow players to combine them to form more complex drawings.

Command-Line Strategy Game: Design a strategy game where players can conquer territories, build armies, and engage in tactical battles. Implement fog of war, unit movement, and resource management.

Text-Based Puzzle Game: Create a puzzle game where players must solve riddles, logic puzzles, and word games to progress through levels. The game can include different categories and difficulty levels.

**Comment by chaitanyasinghnegi** [comment]
done, no need to welcome
